### ISSUE TITLE
fail to build llvm 6.0.0

### ISSUE THREAD

**Issue by longwusha** [termoshtt/llvmenv#21]
i can use my browser to download the source archive  from the same link(http://releases.llvm.org/6.0.0/llvm-6.0.0.src.tar.xz),but llvmenv failed.

anyone can help?

More Info:
lsw@lsw-deepin:~/tools/llvm/6$ RUST_BACKTRACE=1 llvmenv build-entry 6.0.0
Download: http://releases.llvm.org/6.0.0/llvm-6.0.0.src.tar.xz
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io(Custom { kind: WouldBlock, error: StringError("timed out") }), url: None }

stack backtrace:
   0:     0x557f43abd76c - backtrace::backtrace::trace::haf9c4d8d1e10b5d4
   1:     0x557f43abcdc2 - backtrace::capture::Backtrace::new_unresolved::hc7fe874deef8cca0
   2:     0x557f43abc96f - failure::backtrace::internal::InternalBacktrace::new::hb1d59bc9929c5a63
   3:     0x557f43abc631 - failure::backtrace::Backtrace::new::hc0c1cf7573669102
   4:     0x557f438c01bc - llvmenv::entry::download::hc98cc8739ff4f2b9
   5:     0x557f438bca06 - llvmenv::entry::Entry::checkout::h6037f0a016008eb2
   6:     0x557f438cb046 - llvmenv::main::h50ec54bfba91cb4d
   7:     0x557f438b7b06 - std::rt::lang_start::{{closure}}::heac0806c178ff7f4
   8:     0x557f43adc2f2 - std::rt::lang_start_internal::{{closure}}::h342eaeec3a520255
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::h8b090b6144a018fb
                        at libstd/panicking.rs:310
   9:     0x557f43b01d89 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  10:     0x557f43ae68a5 - std::panicking::try::h11349d7f0dce3b3c
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::hfbb0f172d1ed4df2
                        at libstd/panic.rs:374
                         - std::rt::lang_start_internal::h6c73689767a9401e
                        at libstd/rt.rs:58
  11:     0x557f438cc393 - main
  12:     0x7faaeb4132b0 - __libc_start_main
  13:     0x557f4389ec79 - _start
  14:                0x0 - <unknown>', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
   9: llvmenv::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start

**Comment by termoshtt** [comment]
I cannot reproduce it both on 0.1.8 and 0.1.9-alpha. Could you tell me your environment?

**Comment by longwusha** [comment]
llvmenv version is 0.1.8.

the rust version is 1.27.0(installed with rustup).

my operating system is deepin(15.6).

do you need some more detail information?

**Comment by longwusha** [comment]
oh, i am using a proxy tool(i am a chinese).

but this should not be a problem, because this proxy tools is set to work global.

by the way, i can download the llvm source archive from the same link using my bash terminate.

is there any way to set proxy port for llvmenv?

**Comment by termoshtt** [comment]
Hum... I am not familiar with networking. llvmenv uses [reqwest::get](https://docs.rs/reqwest/0.8.6/reqwest/fn.get.html) to download llvm archive file. Could you test it in a minimal setting like:

```rust
extern crate reqwest;
use std::fs;

fn main()  {
    let mut req = reqwest::get("http://releases.llvm.org/6.0.0/llvm-6.0.0.src.tar.xz").expect("GET failed");
    let mut f = fs::File::create("llvm-src.tar.xz").unwrap();
    req.copy_to(&mut f).expect("Copy failed");
}
```

**Comment by longwusha** [comment]
I have tried it, and successfully download llvm archive file.

**Comment by longwusha** [comment]
but llvmenv still fail to download llvm archive file
