### ISSUE TITLE
LaunchFailed Err unwrap

### ISSUE THREAD

**Issue by TheDan64** [termoshtt/llvmenv#30]
After the cfe-6.0.1 download text appears I get:

```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LaunchFailed { cmd: "\"cmake\" \"-DCMAKE_INSTALL_PREFIX=/home/dkolsoi/.local/share/llvmenv/6.0.1\" \"-DCMAKE_BUILD_TYPE=Release\" \"-DLLVM_TARGETS_TO_BUILD=X86\" \"-DLLVM_INCLUDE_EXAMPLES=0\" \"-DCLANG_INCLUDE_EXAMPLES=0\" \"-DLLVM_INCLUDE_DOCS=0\" \"-DCLANG_INCLUDE_DOCS=0\" \"-DLLVM_INCLUDE_TEST=0\" \"-DCLANG_INCLUDE_TEST=0\" \"/home/dkolsoi/.cache/llvmenv/6.0.1\"" }

stack backtrace:
   0:     0x558a971805cc - backtrace::backtrace::trace::h0b04ebb6a9916665
   1:     0x558a9717fbe2 - backtrace::capture::Backtrace::new_unresolved::h941cc4c0eb7c9065
   2:     0x558a9717f70f - failure::backtrace::internal::InternalBacktrace::new::h135d996c20513812
   3:     0x558a9717f991 - <failure::backtrace::Backtrace as core::default::Default>::default::h901006d6fb6f9b1c
   4:     0x558a9717f9c8 - failure::backtrace::Backtrace::new::h2cdae3fbfe2ac0fc
   5:     0x558a96f3f962 - llvmenv::entry::Entry::build::hd199f520a8d2a799
   6:     0x558a96f4c8a0 - llvmenv::main::hbbccda989a099185
   7:     0x558a96f4d479 - std::rt::lang_start::{{closure}}::h43a93f3ee85a2ba7
   8:     0x558a971a24a2 - std::rt::lang_start_internal::{{closure}}::hd1d4b4071b41baca
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::he206d249d44a142e
                        at libstd/panicking.rs:310
   9:     0x558a971c97e9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  10:     0x558a971a4fd5 - std::panicking::try::h26a03cc57bfd493f
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h3b62b18c57da95c7
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::h773ef7be57a5b9c1
                        at libstd/rt.rs:58
  11:     0x558a96f4cf73 - main
  12:     0x7fc115923a86 - __libc_start_main
  13:     0x558a96f173d9 - _start
  14:                0x0 - <unknown>', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: llvmenv::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

when trying to build-entry 6.0.1 in v0.1.9 (linux)

**Comment by termoshtt** [comment]
"Launch Failed" means the command `cmake` not found (sorry for misleading error message). Please install cmake, and confirm it can be called.

**Comment by TheDan64** [comment]
That was indeed the issue, thanks!
